// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BulkSelectController from "./bulk_select_controller"
application.register("bulk-select", BulkSelectController)

import AutosaveController from "./autosave_controller"
application.register("autosave", AutosaveController)

import EventImageCropPreviewController from "./event_image_crop_preview_controller"
application.register("event-image-crop-preview", EventImageCropPreviewController)

import FilterStateController from "./filter_state_controller"
application.register("filter-state", FilterStateController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InfiniteScrollController from "./infinite_scroll_controller"
application.register("infinite-scroll", InfiniteScrollController)

import KeyboardShortcutsController from "./keyboard_shortcuts_controller"
application.register("keyboard-shortcuts", KeyboardShortcutsController)

import NextEventController from "./next_event_controller"
application.register("next-event", NextEventController)

import MergeChangeFilterController from "./merge_change_filter_controller"
application.register("merge-change-filter", MergeChangeFilterController)

import PublicCardStatusController from "./public_card_status_controller"
application.register("public-card-status", PublicCardStatusController)
