// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BulkSelectController from "./bulk_select_controller"
application.register("bulk-select", BulkSelectController)

import AutosaveController from "./autosave_controller"
application.register("autosave", AutosaveController)

import BackendNavMenuController from "./backend_nav_menu_controller"
application.register("backend-nav-menu", BackendNavMenuController)

import BlogPostImagePreuploadController from "./blog_post_image_preupload_controller"
application.register("blog-post-image-preupload", BlogPostImagePreuploadController)

import ConsentController from "./consent_controller"
application.register("consent", ConsentController)

import ConsentMediaController from "./consent_media_controller"
application.register("consent-media", ConsentMediaController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import EditorInboxController from "./editor_inbox_controller"
application.register("editor-inbox", EditorInboxController)

import EventImageCropPreviewController from "./event_image_crop_preview_controller"
application.register("event-image-crop-preview", EventImageCropPreviewController)

import EventImagePreuploadController from "./event_image_preupload_controller"
application.register("event-image-preupload", EventImagePreuploadController)

import EventImageEditorUploadController from "./event_image_editor_upload_controller"
application.register("event-image-editor-upload", EventImageEditorUploadController)

import EventEditorTabsController from "./event_editor_tabs_controller"
application.register("event-editor-tabs", EventEditorTabsController)

import FilterStateController from "./filter_state_controller"
application.register("filter-state", FilterStateController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HeroRotatorController from "./hero_rotator_controller"
application.register("hero-rotator", HeroRotatorController)

import HighlightsSliderController from "./highlights_slider_controller"
application.register("highlights-slider", HighlightsSliderController)

import InfiniteScrollController from "./infinite_scroll_controller"
application.register("infinite-scroll", InfiniteScrollController)

import KeyboardShortcutsController from "./keyboard_shortcuts_controller"
application.register("keyboard-shortcuts", KeyboardShortcutsController)

import LightboxController from "./lightbox_controller"
application.register("lightbox", LightboxController)

import NextEventController from "./next_event_controller"
application.register("next-event", NextEventController)

import MergeChangeFilterController from "./merge_change_filter_controller"
application.register("merge-change-filter", MergeChangeFilterController)

import MobileNavController from "./mobile_nav_controller"
application.register("mobile-nav", MobileNavController)

import NavOffsetController from "./nav_offset_controller"
application.register("nav-offset", NavOffsetController)

import PublicCardStatusController from "./public_card_status_controller"
application.register("public-card-status", PublicCardStatusController)

import PublicSearchController from "./public_search_controller"
application.register("public-search", PublicSearchController)

import PromotionBannerImagePreuploadController from "./promotion_banner_image_preupload_controller"
application.register("promotion-banner-image-preupload", PromotionBannerImagePreuploadController)

import ScrollTopController from "./scroll_top_controller"
application.register("scroll-top", ScrollTopController)

import SectionViewController from "./section_view_controller"
application.register("section-view", SectionViewController)

import SettingsSortableController from "./settings_sortable_controller"
application.register("settings-sortable", SettingsSortableController)

import SettingsTabsController from "./settings_tabs_controller"
application.register("settings-tabs", SettingsTabsController)
