production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12

  daily_import_runs:
    command: "Importing::DailyRunJob.perform_later"
    schedule: every day at 3:05am

  daily_merge_run:
    command: "Merging::DailyRunJob.perform_later"
    schedule: every day at 4:05am

  daily_llm_enrichment_run:
    command: "Importing::LlmEnrichment::DailyRunJob.perform_later"
    schedule: every day at 6:05am

  daily_event_retention_cleanup:
    command: "Events::Retention::PruneStaleUnpublishedEventsJob.perform_later"
    schedule: every day at 7:05am

  daily_raw_event_import_retention_cleanup:
    command: "Events::Retention::PrunePastRawEventImportsJob.perform_later"
    schedule: every day at 7:20am
